### ISSUE TITLE
Ошибка десериализации users.get

### ISSUE THREAD

**Issue by birdy90** [VKCOM/vk-windowsphone-sdk#11]
Добрый день. Уже несколько дней ломаю голову над тем, что я мог сделать не так, но как-будто всё верно - не получается получить данные по запросу `users.get`. Нужно это для того, чтобы получить имя текущего пользователя.
Первый вариант:
![default](https://cloud.githubusercontent.com/assets/4995346/12451078/5b3c1fb4-bf98-11e5-92c2-88d5212f27c2.PNG)
Второй вариант:
![2](https://cloud.githubusercontent.com/assets/4995346/12451146/b4bfe3ea-bf98-11e5-9778-29bce99fd9b1.PNG)
На картинках видно приходящую строку с json и результат запроса (в двух вариантах - VKUser и VKList<VKUser>). Пробовал также вариант и со статическим методом:
`VKRequest.Dispatch<VKList<VKUser>>(new VKRequestParameters("users.get", "fields", ""), (res) => ...`
К слову, дальше я делаю запрос на получение групп пользователя, и он прекрасно работает:
`VKRequest.Dispatch<VKList<VKGroup>>(new VKRequestParameters("groups.get", "extended", "1"), (res) => ...`
Разрабатываю в vs 2015, тестирование на устройстве (lumia 640)

**Comment by alexsychev** [comment]
users.get возвращает простой (без count) список пользователей. Соответственно, использовать надо List<VKUser>,а не VKList<VKUser>.

**Comment by birdy90** [comment]
Огромное спасибо, я был очень близок, но меня озадачило то, что если делать запрос через статический метод, то простой List не хочет компилироваться:
![default](https://cloud.githubusercontent.com/assets/4995346/12463952/95299046-bfd7-11e5-87f5-4b51bbb5d93c.PNG)
А может быть смог бы, но я как-то не додумался, как заставить его собраться с List и статическим методом.
