### ISSUE TITLE
Работа VK SDK при установке .xap файла по проводу / из маркета, что меняется ? 

### ISSUE THREAD

**Issue by ALLMOBILE** [VKCOM/vk-windowsphone-sdk#13]
Нужна консультация, столкнулись с проблемой, мы сделали следующие действия по интеграции VK SDK в нашу игру:

1) Обновили Windows Phone Silverlight 8.0 приложение до Windows Phone Silverlight 8.1

 https://habrahabr.ru/company/microsoft/blog/230015/ 

2) Встроили SDK

https://github.com/VKCOM/vk-windowsphone-sdk/tree/master/SDKSample81

3) У нас все работает (авторизация через сайт и через приложение),
если мы ставим XAP "файл по проводу", но все перестает работать после 
того как приложение публикуется в маркете.

Авторизация через сайт зависает после ввода логина и пароля на странице,
а авторизация через приложение просто выдает белый экран со словом Ошибка.

Вероятно что-то происходит с приложением в момент публикации что делает
версию отгружаемую из маркета "не рабочей" ... 

Возможно кто-то раньше уже попадал на эту проблему и смог ее решить ? 

Возможно по ответу выше мы что-то сделали принципиально не правильно или
для работы именно релизной версии нужны действия по включению SDK на
Вашей стороне ?

**Comment by alexsychev** [comment]
Здравствуйте. Можно ссылку на опубликованную игру?

**Comment by ALLMOBILE** [comment]
Проблема оказалась в том что мы прописали в поле Windows App ID старый ID приложения (в формате 7.1+ версии), 
а сейчас изменился формат и это уже называется Package/Identity/Name (достаточно было внести правильные данные в ВК админку).

Версия установленная по проводу - работала и так.

http://www.windowsphone.com/s?appid=7af380ff-b401-426e-a322-393f3ed5734f
