### ISSUE TITLE
Windows Phone 8.1 Universal App

### ISSUE THREAD

**Issue by DRybochkin** [VKCOM/vk-windowsphone-sdk#4]
Hi, do you planning to release a version for Windows Phone 8.1?

**Comment by Vdimir** [comment]
На данный момент возможно работать с wp8.1, в решении есть соответствующие проекты.
Issue не актуально?

**Comment by DRybochkin** [comment]
Не актуально, уже сделал сам еще в январе.

**Comment by Vdimir** [comment]
@DRybochkin Вы дополнили текущее решение или написали полностью свое? Интересует эта тема, если сможете ответить на пару вопросов, скажите как с Вами связаться

**Comment by DRybochkin** [comment]
Скорее доработал, но кое-что изменил.
 d-rybochkin@ya.ru
