### ISSUE TITLE
не сохраняется access token

### ISSUE THREAD

**Issue by otez-jedi** [VKCOM/vk-windowsphone-sdk#7]
когда sdk получает access token после успешной авторизации, то его значение записывается в IsolatedStorageSettings.ApplicationSettings. при этом не вызывается iso.Save(), что ведет к потере данных при перезапуске приложения.
см. VKAccessToken.cs line:61

**Comment by alexsychev** [comment]
ApplicationSettings должны сохраняться автоматически. Вызов Save не требуется.

Date: Wed, 9 Sep 2015 02:21:52 -0700

**Comment by otez-jedi** [comment]
The IsolatedStorageSettings class is not automatically saved
to disk when values are written. Saves are done in a finalizer, which is
usually but not always run when the application shuts down. To ensure saves are
actually performed we need to call the Save method after each write or set of
writes.

https://msdn.microsoft.com/en-US/library/system.io.isolatedstorage.isolatedstoragesettings%28v=vs.95%29.aspx

**Comment by alexsychev** [comment]
Исправил.

Date: Thu, 10 Sep 2015 02:28:11 -0700
