### ISSUE TITLE
Аутентификация через приложение на winphone8

### ISSUE THREAD

**Issue by DrMoriarty** [VKCOM/vk-windowsphone-sdk#9]
Добрый день.
Я делаю плагин для VK SDK под универсальную виндовс (из винфоновского) для Cordova.
Текущая версия находится тут https://github.com/DrMoriarty/cordova-social-vk/tree/windows

Плагин успешно проходит аутентификацию с помощью IE, но если на телефоне установлено приложение VK, тогда аутентификация не удаётся. После ввода логина и пароля приложение открывает пустой экран с надписью Ошибка и управление обратно в вызвавшее приложение не передаётся.

![twuq79ufeiw](https://cloud.githubusercontent.com/assets/1177068/11678409/bc6575a8-9e58-11e5-944a-9238e2b5d04b.jpg)

**Comment by birdy90** [comment]
Не знаю, насколько это актуально, но сталкивался с этим, когда делал авторизацию через WebView, и при этом у телефона не было подключения к интернету. Как только подключение появлялось - эта ошибка не показывалась. Проверить наличие подключения можно функцией `NetworkInterface.GetIsNetworkAvailable()`

**Comment by DrMoriarty** [comment]
Данная конкретная проблема была вызвана тем, что в настройках приложения ВК был указан другой идентификатор нативного приложения.
